version: '2.1'

services:
  koa-typescript:
    image: koa-typescript
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8085:8085
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js